apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: default
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: phpmyadmin
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        args:
          - sleep
          - infinity
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: phpport
