FROM    alpine:3.12.1
#install stuff
RUN     apk add \
        wget \
        openrc \
        lighttpd \
        php7-common \
        php7-iconv \
        php7-json \
        php7-gd \
        php7-curl \
        php7-xml \
        php7-mysqli \
        php7-imap \
        php7-cgi \
        fcgi \
        php7-pdo \
        php7-pdo_mysql \
        php7-soap \
        php7-xmlrpc \
        php7-posix \
        php7-mcrypt \
        php7-gettext \
        php7-ldap \
        php7-ctype \
        php7-dom
#delete and copy new lighttpd.conf
RUN     rm -rf /etc/lighttpd/lighttpd.conf
COPY    ./lighttpd.conf ./etc/lighttpd/lighttpd.conf
#set lighttpd as default
RUN     rc-update add lighttpd default
#enable php extension
RUN     apk add mysql mysql-client
#RUN     apk add mysql mysql-client php-mysql php-mysqli
FROM    php:7-fpm-alpine
RUN     docker-php-ext-install mysqli
#change directory
#RUN     mysql_install_db --basedir=/usr/local

#add user
#RUN     /usr/bin/mysql_install_db --user=mysql
RUN     /usr/bin/mysql_install_db --user=mysql
#init mysql and set as default
RUN     /etc/init.d/mysql start && rc-update add mysql default
#create mysql user
RUN     /usr/bin/mysqladmin -u root password 'password'
#create folder where phpmyadmin will be installed
RUN     mkdir -p /usr/share/webapps/
#download
RUN     wget http://files.directadmin.com/services/all/phpMyAdmin/phpMyAdmin-5.0.2-all-languages.tar.gz -O /usr/share/webapps
#uncompress
RUN     tar zxvf /usr/share/webapps/phpMyAdmin-5.0.2-all-languages.tar.gz
#delete left overs
RUN     rm /usr/share/webapps/phpMyAdmin-5.0.2-all-languages.tar.gz
#rename
RUN     mv /usr/share/webapps/phpMyAdmin-5.0.2-all-languages /usr/share/webapps/phpmyadmin
#give permissions
RUN     chmod -R 777 /usr/share/webapps/
#create sim links
RUN     ln -s /usr/share/webapps/phpmyadmin/ /var/www/localhost/htdocs/phpmyadmin

EXPOSE  80 5000
